//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pismovoditel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskEventLog
    {
        public int LogId { get; set; }
        public System.DateTime ChangeTime { get; set; }
        public int ActorId { get; set; }
        public int TaskId { get; set; }
        public int EventTypeId { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<int> Int1 { get; set; }
        public Nullable<int> Int2 { get; set; }
        public string string1 { get; set; }
        public string string2 { get; set; }
    }
}
