//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pismovoditel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskLog
    {
        public int LogId { get; set; }
        public System.DateTime ChangeTime { get; set; }
        public Nullable<int> ActorId { get; set; }
        public int TaskId { get; set; }
        public int ProjectId { get; set; }
        public string TaskName { get; set; }
        public string TaskBody { get; set; }
        public Nullable<int> TaskExecutorId { get; set; }
        public Nullable<System.DateTime> TillDate { get; set; }
        public int TaskTypeId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Priority Priority { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
        public virtual TaskType TaskType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
